export type Role=string;
export type User={id:number;email:string;role:Role;disabled:boolean};
export type PermissionKey='proxy_hosts.read'|'proxy_hosts.write'|'certificates.read'|'certificates.write'|'users.manage'|'roles.manage'|'audit_logs.read'|'audit_logs.export'|'system.settings.manage'|'sessions.revoke'|'bot_protection.manage';
export type RolePermissionScope={permission:'proxy_hosts.read'|'proxy_hosts.write';proxy_host_ids:number[]};
export type RoleRecord={id:number;slug:string;name:string;description:string;system_managed:boolean;permissions:PermissionKey[];scopes?:RolePermissionScope[]};
export type Host={id:number;name:string;domain:string;upstream_host:string;upstream_port:number;tls_mode:string;certificate_id:number|null;enabled:boolean};
export type Certificate={id:number;name:string;source:string;covered_hostnames:string[];expiry:string;active:boolean;acme?:AcmeStatus|null};
export type AcmeRequest={environment:'staging'|'production';challenge:'http01'|'cloudflare_dns01';hostnames:string[];cloudflare_api_token?:string};
export type AcmeJob={job_id:string;certificate_id:number|null;status:string};
export type AcmeStatus={certificate_id:number;environment:'staging'|'production';challenge:'http01'|'cloudflare_dns01';hostnames:string[];renewal_state:string;next_renewal_at:string|null;last_attempt_at:string|null;last_error_code:string|null};
export type AuditLogItem={id:number;actor:string;event:string;details:string;created_at:string};
export type AuditLogPage={items:AuditLogItem[];page:number;page_size:number;total:number};
export type AuditLogQuery={event?:string;actor_id?:number;from?:string;to?:string;q?:string;page?:number;page_size?:number};
export type WafMode='monitor-only'|'block';
export type WafAction='inherit'|'allow'|'log'|'block';
export type WafConfig={mode:WafMode;updated_at:string};
export type WafRule={id:number;name:string;source:string;category:string;severity:string;enabled:boolean;action:WafAction;matcher_json:string;created_at:string;updated_at:string};
export type BotMode='monitor'|'challenge'|'block';
export type BotConfig={mode:BotMode;threshold:number;ttl_seconds:number;updated_at:string};
export type TrustedCrawler={id:number;category:'trusted_crawler';weight:number;trusted_user_agent:string|null;trusted_domain:string|null;enabled:boolean};
export type BotChallenge={token:string;difficulty:number;expires_at:number;fingerprint_prefix:string};
export type RateLimitAction='monitor'|'block';
export type RateLimitKeyScope='proxy_host_ip';
export type RateLimitConfig={enabled:boolean;action:RateLimitAction;capacity:number;refill_per_second:number;key_scope:RateLimitKeyScope;updated_at:string};
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const r=await fetch(path,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok){const e=await r.json().catch(()=>({message:r.statusText}));const error=new Error(typeof e.message==='string'?e.message:'Request failed') as Error & {status?:number};error.status=r.status;throw error}return r.status===204?undefined as T:r.json()}
async function requestText(path:string):Promise<string>{const r=await fetch(path,{credentials:'include'});if(!r.ok)throw Object.assign(new Error('Request failed'),{status:r.status});return r.text()}
export const api={
 status:()=>request<{initialized:boolean}>('/api/setup/status'),setup:(x:object)=>request<User>('/api/setup/initialize',{method:'POST',body:JSON.stringify(x)}),login:(x:object)=>request<User>('/api/auth/login',{method:'POST',body:JSON.stringify(x)}),me:()=>request<User>('/api/auth/me'),logout:()=>request<void>('/api/auth/logout',{method:'POST'}),
 hosts:()=>request<Host[]>('/api/proxy-hosts'),createHost:(x:object)=>request<Host>('/api/proxy-hosts',{method:'POST',body:JSON.stringify(x)}),updateHost:(id:number,x:object)=>request<Host>(`/api/proxy-hosts/${id}`,{method:'PATCH',body:JSON.stringify(x)}),deleteHost:(id:number)=>request<void>(`/api/proxy-hosts/${id}`,{method:'DELETE'}),
 certificates:()=>request<Certificate[]>('/api/certificates'),issueAcme:(x:AcmeRequest)=>request<AcmeJob>('/api/certificates/acme',{method:'POST',body:JSON.stringify(x)}),renewCertificate:(id:number)=>request<AcmeJob>(`/api/certificates/${id}/renew`,{method:'POST'}),certificateStatus:(id:number)=>request<AcmeStatus>(`/api/certificates/${id}/status`),activateCertificate:(id:number)=>request<void>(`/api/certificates/${id}/activate`,{method:'POST'}),
 users:()=>request<User[]>('/api/users'),createUser:(x:{email:string;password:string;role:Role})=>request<User>('/api/users',{method:'POST',body:JSON.stringify(x)}),updateUser:(id:number,x:{role?:Role;disabled?:boolean})=>request<User>(`/api/users/${id}`,{method:'PATCH',body:JSON.stringify(x)}),deleteUser:(id:number)=>request<void>(`/api/users/${id}`,{method:'DELETE'}),revokeUserSessions:(id:number)=>request<{revoked:number}>(`/api/users/${id}/sessions/revoke`,{method:'POST'}),
 roles:()=>request<RoleRecord[]>('/api/roles'),createRole:(x:{slug:string;name:string;description:string;permissions:PermissionKey[];scopes?:RolePermissionScope[]})=>request<RoleRecord>('/api/roles',{method:'POST',body:JSON.stringify(x)}),updateRole:(id:number,x:Partial<{name:string;description:string;permissions:PermissionKey[];scopes:RolePermissionScope[]}>)=>request<RoleRecord>(`/api/roles/${id}`,{method:'PATCH',body:JSON.stringify(x)}),deleteRole:(id:number)=>request<void>(`/api/roles/${id}`,{method:'DELETE'}),
 auditLogs:(query:AuditLogQuery={})=>{const params=new URLSearchParams();for(const [key,value] of Object.entries(query)){if(value!==undefined&&value!=='')params.set(key,String(value))}const suffix=params.toString()?`?${params.toString()}`:'';return request<AuditLogPage>(`/api/audit-logs${suffix}`)}
 ,wafConfig:()=>request<WafConfig>('/api/waf/config'),wafRules:()=>request<WafRule[]>('/api/waf/rules'),updateWafConfig:(x:{mode:WafMode})=>request<WafConfig>('/api/waf/config',{method:'PATCH',body:JSON.stringify(x)}),createWafRule:(x:object)=>request<WafRule>('/api/waf/rules',{method:'POST',body:JSON.stringify(x)}),updateWafRule:(id:number,x:object)=>request<WafRule>(`/api/waf/rules/${id}`,{method:'PATCH',body:JSON.stringify(x)}),deleteWafRule:(id:number)=>request<void>(`/api/waf/rules/${id}`,{method:'DELETE'}),importWafRules:(toml:string)=>request<void>('/api/waf/rules/import',{method:'POST',headers:{'Content-Type':'application/toml'},body:toml}),exportWafRules:()=>requestText('/api/waf/rules/export'),
 botConfig:()=>request<BotConfig>('/api/bot/config'),updateBotConfig:(x:Partial<{mode:BotMode;threshold:number;ttl_seconds:number}>)=>request<BotConfig>('/api/bot/config',{method:'PATCH',body:JSON.stringify(x)}),trustedCrawlers:()=>request<TrustedCrawler[]>('/api/bot/trusted-crawlers'),createTrustedCrawler:(x:{user_agent:string;domain:string;enabled?:boolean})=>request<TrustedCrawler>('/api/bot/trusted-crawlers',{method:'POST',body:JSON.stringify(x)}),updateTrustedCrawler:(id:number,x:{user_agent:string;domain:string;enabled?:boolean})=>request<TrustedCrawler>(`/api/bot/trusted-crawlers/${id}`,{method:'PATCH',body:JSON.stringify(x)}),deleteTrustedCrawler:(id:number)=>request<void>(`/api/bot/trusted-crawlers/${id}`,{method:'DELETE'}),botChallenge:(fingerprint:string)=>request<BotChallenge>('/api/bot/challenge',{method:'POST',body:JSON.stringify({fingerprint})}),verifyBotChallenge:(x:{token:string;fingerprint:string;solution:string})=>request<{ok:boolean}>('/api/bot/challenge/verify',{method:'POST',body:JSON.stringify(x)}),importBotConfig:(toml:string)=>request<void>('/api/bot/config/import',{method:'POST',headers:{'Content-Type':'application/toml'},body:toml}),exportBotConfig:()=>requestText('/api/bot/config/export')
 ,rateLimitConfig:()=>request<RateLimitConfig>('/api/rate-limit/config'),updateRateLimitConfig:(x:Pick<RateLimitConfig,'enabled'|'action'|'capacity'|'refill_per_second'|'key_scope'>)=>request<RateLimitConfig>('/api/rate-limit/config',{method:'PATCH',body:JSON.stringify(x)})
};
